namespace: "ari_stark"
name: "ansible_oracle_modules"
version: "1.3.0"
readme: "README.md"
authors:
  - "Ari Stark"
  - "Mikael Sandström <oravirt@gmail.com>"
  - "Denis Barleben <denis.barleben@kobil.com>"
description: "Modules for working with Oracle Database"
license:
  - "MIT"
tags:
  - "oracle"
repository: "https://github.com/ari-stark/ansible-oracle-modules"
homepage: "https://github.com/ari-stark/ansible-oracle-modules"
issues: "https://github.com/ari-stark/ansible-oracle-modules/issues"
build_ignore:
  - ".idea"
  - ".gitignore"
  - "ansible_collections"
  - "build_collection.yml"
  - "requirements.txt"
  - "tests/output"
  - "tests/toto.*"
  - "venv"
  - "*.tar.gz"
